// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq6pvj5ZN0sLm_Gu9Hp-jF6Qqcxd_A-sA',
    appId: '1:96522945588:web:54c16f99fbb02c53a57661',
    messagingSenderId: '96522945588',
    projectId: 'finalyearproject-e0d56',
    authDomain: 'finalyearproject-e0d56.firebaseapp.com',
    storageBucket: 'finalyearproject-e0d56.firebasestorage.app',
    measurementId: 'G-4TZXX06HCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZzQxOsbE0gDRqiZA0lHbGN6PjD9S9lI',
    appId: '1:96522945588:android:1baa88ea041db381a57661',
    messagingSenderId: '96522945588',
    projectId: 'finalyearproject-e0d56',
    storageBucket: 'finalyearproject-e0d56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_ezMcPp1PEM-MikrvpaNPx1wL4nvatnk',
    appId: '1:96522945588:ios:1baec5eddc40bba1a57661',
    messagingSenderId: '96522945588',
    projectId: 'finalyearproject-e0d56',
    storageBucket: 'finalyearproject-e0d56.firebasestorage.app',
    iosBundleId: 'com.example.finalyearproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_ezMcPp1PEM-MikrvpaNPx1wL4nvatnk',
    appId: '1:96522945588:ios:1baec5eddc40bba1a57661',
    messagingSenderId: '96522945588',
    projectId: 'finalyearproject-e0d56',
    storageBucket: 'finalyearproject-e0d56.firebasestorage.app',
    iosBundleId: 'com.example.finalyearproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq6pvj5ZN0sLm_Gu9Hp-jF6Qqcxd_A-sA',
    appId: '1:96522945588:web:a00672bf784b803ca57661',
    messagingSenderId: '96522945588',
    projectId: 'finalyearproject-e0d56',
    authDomain: 'finalyearproject-e0d56.firebaseapp.com',
    storageBucket: 'finalyearproject-e0d56.firebasestorage.app',
    measurementId: 'G-7N01G2T0TF',
  );
}
